server:
  port: 8080

jwt:
  secret: "myverysecuresecretkeythatis256bitlong!!"

file:
  upload-dir: uploads # Directory to store uploaded files

spring:
  servlet:
    multipart:
      max-file-size: 10MB # Maximum size of a single uploaded file
      max-request-size: 10MB # Maximum total size of the request
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Automatically create/update schema
  h2:
    console:
      enabled: true  # Enable the H2 Console
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cache:
    type: simple # Use simple in-memory caching
springdoc:
  api-docs:
    enabled: true  # Enable OpenAPI docs generation
    path: /v3/api-docs  # Path for API documentation JSON file
  swagger-ui:
    enabled: true  # Enable Swagger UI
    path: /swagger-ui.html  # Path to Swagger UI
    url: /v3/api-docs  # URL where Swagger UI fetches the OpenAPI docs
    display-operation-id: true  # Show operation IDs in Swagger UI
    display-request-duration: true  # Display request duration in Swagger UI
    doc-expansion: list  # Expand API methods on load, list all methods

logging:
  level:
    org.springframework.cache: DEBUG

management:
  metrics:
    enable:
      cache: true  # Enable cache metrics
  endpoints:
    web:
      exposure:
        include: "metrics"  # Expose the metrics endpoint

